export const dataArray = [
  {
    col1: "origin 1 - Incoming",
    col2: "Gateway 1",
    col3: "Status",
    col4: "Account One",
    col5: "00:04:32",
  },
  {
    col1: "origin 2 - Incoming",
    col2: "Gateway 1",
    col3: "Status",
    col4: "Account Two",
    col5: "00:03:32",
  },
  {
    col1: "origin 3 - Outgoing",
    col2: "Gateway 2",
    col3: "Status",
    col4: "Account Three",
    col5: "00:03:02",
  },
  {
    col1: "origin 4 - Incoming",
    col2: "Gateway 3",
    col3: "Status",
    col4: "Account Four",
    col5: "00:02:52",
  },
  {
    col1: "origin 5 - Incoming",
    col2: "Gateway 1",
    col3: "Status",
    col4: "Account Five",
    col5: "00:02:45",
  },
  {
    col1: "origin 6 - Incoming",
    col2: "Gateway 1",
    col3: "Status",
    col4: "Account Six",
    col5: "00:04:32",
  },
  {
    col1: "origin 7 - Incoming",
    col2: "Gateway 1",
    col3: "Status",
    col4: "Account Seven",
    col5: "00:04:32",
  },
  {
    col1: "origin 8 - Incoming",
    col2: "Gateway 1",
    col3: "Status",
    col4: "Account Eight",
    col5: "00:04:32",
  },
  {
    col1: "origin 8 - Incoming",
    col2: "Gateway 1",
    col3: "Status",
    col4: "Account Eight",
    col5: "00:04:32",
  },
  {
    col1: "origin 8 - Incoming",
    col2: "Gateway 1",
    col3: "Status",
    col4: "Account Eight",
    col5: "00:04:32",
  },
  {
    col1: "origin 8 - Incoming",
    col2: "Gateway 1",
    col3: "Status",
    col4: "Account Eight",
    col5: "00:04:32",
  },
  {
    col1: "origin 8 - Incoming",
    col2: "Gateway 1",
    col3: "Status",
    col4: "Account Eight",
    col5: "00:04:32",
  },
  {
    col1: "origin 8 - Incoming",
    col2: "Gateway 1",
    col3: "Status",
    col4: "Account Eight",
    col5: "00:04:32",
  },
  {
    col1: "origin 8 - Incoming",
    col2: "Gateway 1",
    col3: "Status",
    col4: "Account Eight",
    col5: "00:04:32",
  },
  {
    col1: "origin 8 - Incoming",
    col2: "Gateway 1",
    col3: "Status",
    col4: "Account Eight",
    col5: "00:04:32",
  },
  {
    col1: "origin 8 - Incoming",
    col2: "Gateway 1",
    col3: "Status",
    col4: "Account Eight",
    col5: "00:04:32",
  },
  {
    col1: "origin 8 - Incoming",
    col2: "Gateway 1",
    col3: "Status",
    col4: "Account Eight",
    col5: "00:04:32",
  },
  {
    col1: "origin 8 - Incoming",
    col2: "Gateway 1",
    col3: "Status",
    col4: "Account Eight",
    col5: "00:04:32",
  },
  {
    col1: "origin 1 - Incoming",
    col2: "Gateway 1",
    col3: "Status",
    col4: "Account One",
    col5: "00:04:32",
  },
  {
    col1: "origin 2 - Incoming",
    col2: "Gateway 1",
    col3: "Status",
    col4: "Account Two",
    col5: "00:03:32",
  },
  {
    col1: "origin 3 - Outgoing",
    col2: "Gateway 2",
    col3: "Status",
    col4: "Account Three",
    col5: "00:03:02",
  },
  {
    col1: "origin 4 - Incoming",
    col2: "Gateway 3",
    col3: "Status",
    col4: "Account Four",
    col5: "00:02:52",
  },
  {
    col1: "origin 5 - Incoming",
    col2: "Gateway 1",
    col3: "Status",
    col4: "Account Five",
    col5: "00:02:45",
  },
  {
    col1: "origin 6 - Incoming",
    col2: "Gateway 1",
    col3: "Status",
    col4: "Account Six",
    col5: "00:04:32",
  },
  {
    col1: "origin 7 - Incoming",
    col2: "Gateway 1",
    col3: "Status",
    col4: "Account Seven",
    col5: "00:04:32",
  },
  {
    col1: "origin 8 - Incoming",
    col2: "Gateway 1",
    col3: "Status",
    col4: "Account Eight",
    col5: "00:04:32",
  },
  {
    col1: "origin 8 - Incoming",
    col2: "Gateway 1",
    col3: "Status",
    col4: "Account Eight",
    col5: "00:04:32",
  },
  {
    col1: "origin 8 - Incoming",
    col2: "Gateway 1",
    col3: "Status",
    col4: "Account Eight",
    col5: "00:04:32",
  },
  {
    col1: "origin 8 - Incoming",
    col2: "Gateway 1",
    col3: "Status",
    col4: "Account Eight",
    col5: "00:04:32",
  },
  {
    col1: "origin 8 - Incoming",
    col2: "Gateway 1",
    col3: "Status",
    col4: "Account Eight",
    col5: "00:04:32",
  },
  {
    col1: "origin 8 - Incoming",
    col2: "Gateway 1",
    col3: "Status",
    col4: "Account Eight",
    col5: "00:04:32",
  },
  {
    col1: "origin 8 - Incoming",
    col2: "Gateway 1",
    col3: "Status",
    col4: "Account Eight",
    col5: "00:04:32",
  },
  {
    col1: "origin 8 - Incoming",
    col2: "Gateway 1",
    col3: "Status",
    col4: "Account Eight",
    col5: "00:04:32",
  },
  {
    col1: "origin 8 - Incoming",
    col2: "Gateway 1",
    col3: "Status",
    col4: "Account Eight",
    col5: "00:04:32",
  },
  {
    col1: "origin 8 - Incoming",
    col2: "Gateway 1",
    col3: "Status",
    col4: "Account Eight",
    col5: "00:04:32",
  },
  {
    col1: "origin 8 - Incoming",
    col2: "Gateway 1",
    col3: "Status",
    col4: "Account Eight",
    col5: "00:04:32",
  },
  {
    col1: "origin 1 - Incoming",
    col2: "Gateway 1",
    col3: "Status",
    col4: "Account One",
    col5: "00:04:32",
  },
  {
    col1: "origin 2 - Incoming",
    col2: "Gateway 1",
    col3: "Status",
    col4: "Account Two",
    col5: "00:03:32",
  },
  {
    col1: "origin 3 - Outgoing",
    col2: "Gateway 2",
    col3: "Status",
    col4: "Account Three",
    col5: "00:03:02",
  },
  {
    col1: "origin 4 - Incoming",
    col2: "Gateway 3",
    col3: "Status",
    col4: "Account Four",
    col5: "00:02:52",
  },
  {
    col1: "origin 5 - Incoming",
    col2: "Gateway 1",
    col3: "Status",
    col4: "Account Five",
    col5: "00:02:45",
  },
  {
    col1: "origin 6 - Incoming",
    col2: "Gateway 1",
    col3: "Status",
    col4: "Account Six",
    col5: "00:04:32",
  },
  {
    col1: "origin 7 - Incoming",
    col2: "Gateway 1",
    col3: "Status",
    col4: "Account Seven",
    col5: "00:04:32",
  },
  {
    col1: "origin 8 - Incoming",
    col2: "Gateway 1",
    col3: "Status",
    col4: "Account Eight",
    col5: "00:04:32",
  },
  {
    col1: "origin 8 - Incoming",
    col2: "Gateway 1",
    col3: "Status",
    col4: "Account Eight",
    col5: "00:04:32",
  },
  {
    col1: "origin 8 - Incoming",
    col2: "Gateway 1",
    col3: "Status",
    col4: "Account Eight",
    col5: "00:04:32",
  },
  {
    col1: "origin 8 - Incoming",
    col2: "Gateway 1",
    col3: "Status",
    col4: "Account Eight",
    col5: "00:04:32",
  },
  {
    col1: "origin 8 - Incoming",
    col2: "Gateway 1",
    col3: "Status",
    col4: "Account Eight",
    col5: "00:04:32",
  },
  {
    col1: "origin 8 - Incoming",
    col2: "Gateway 1",
    col3: "Status",
    col4: "Account Eight",
    col5: "00:04:32",
  },
  {
    col1: "origin 8 - Incoming",
    col2: "Gateway 1",
    col3: "Status",
    col4: "Account Eight",
    col5: "00:04:32",
  },
  {
    col1: "origin 8 - Incoming",
    col2: "Gateway 1",
    col3: "Status",
    col4: "Account Eight",
    col5: "00:04:32",
  },
  {
    col1: "origin 8 - Incoming",
    col2: "Gateway 1",
    col3: "Status",
    col4: "Account Eight",
    col5: "00:04:32",
  },
  {
    col1: "origin 8 - Incoming",
    col2: "Gateway 1",
    col3: "Status",
    col4: "Account Eight",
    col5: "00:04:32",
  },
  {
    col1: "origin 8 - Incoming",
    col2: "Gateway 1",
    col3: "Status",
    col4: "Account Eight",
    col5: "00:04:32",
  },
  {
    col1: "origin 1 - Incoming",
    col2: "Gateway 1",
    col3: "Status",
    col4: "Account One",
    col5: "00:04:32",
  },
  {
    col1: "origin 2 - Incoming",
    col2: "Gateway 1",
    col3: "Status",
    col4: "Account Two",
    col5: "00:03:32",
  },
  {
    col1: "origin 3 - Outgoing",
    col2: "Gateway 2",
    col3: "Status",
    col4: "Account Three",
    col5: "00:03:02",
  },
  {
    col1: "origin 4 - Incoming",
    col2: "Gateway 3",
    col3: "Status",
    col4: "Account Four",
    col5: "00:02:52",
  },
  {
    col1: "origin 5 - Incoming",
    col2: "Gateway 1",
    col3: "Status",
    col4: "Account Five",
    col5: "00:02:45",
  },
  {
    col1: "origin 6 - Incoming",
    col2: "Gateway 1",
    col3: "Status",
    col4: "Account Six",
    col5: "00:04:32",
  },
  {
    col1: "origin 7 - Incoming",
    col2: "Gateway 1",
    col3: "Status",
    col4: "Account Seven",
    col5: "00:04:32",
  },
  {
    col1: "origin 8 - Incoming",
    col2: "Gateway 1",
    col3: "Status",
    col4: "Account Eight",
    col5: "00:04:32",
  },
  {
    col1: "origin 8 - Incoming",
    col2: "Gateway 1",
    col3: "Status",
    col4: "Account Eight",
    col5: "00:04:32",
  },
  {
    col1: "origin 8 - Incoming",
    col2: "Gateway 1",
    col3: "Status",
    col4: "Account Eight",
    col5: "00:04:32",
  },
  {
    col1: "origin 8 - Incoming",
    col2: "Gateway 1",
    col3: "Status",
    col4: "Account Eight",
    col5: "00:04:32",
  },
  {
    col1: "origin 8 - Incoming",
    col2: "Gateway 1",
    col3: "Status",
    col4: "Account Eight",
    col5: "00:04:32",
  },
  {
    col1: "origin 8 - Incoming",
    col2: "Gateway 1",
    col3: "Status",
    col4: "Account Eight",
    col5: "00:04:32",
  },
  {
    col1: "origin 8 - Incoming",
    col2: "Gateway 1",
    col3: "Status",
    col4: "Account Eight",
    col5: "00:04:32",
  },
  {
    col1: "origin 8 - Incoming",
    col2: "Gateway 1",
    col3: "Status",
    col4: "Account Eight",
    col5: "00:04:32",
  },
  {
    col1: "origin 8 - Incoming",
    col2: "Gateway 1",
    col3: "Status",
    col4: "Account Eight",
    col5: "00:04:32",
  },
  {
    col1: "origin 8 - Incoming",
    col2: "Gateway 1",
    col3: "Status",
    col4: "Account Eight",
    col5: "00:04:32",
  },
  {
    col1: "origin 8 - Incoming",
    col2: "Gateway 1",
    col3: "Status",
    col4: "Account Eight",
    col5: "00:04:32",
  },
  {
    col1: "origin 1 - Incoming",
    col2: "Gateway 1",
    col3: "Status",
    col4: "Account One",
    col5: "00:04:32",
  },
  {
    col1: "origin 2 - Incoming",
    col2: "Gateway 1",
    col3: "Status",
    col4: "Account Two",
    col5: "00:03:32",
  },
  {
    col1: "origin 3 - Outgoing",
    col2: "Gateway 2",
    col3: "Status",
    col4: "Account Three",
    col5: "00:03:02",
  },
  {
    col1: "origin 4 - Incoming",
    col2: "Gateway 3",
    col3: "Status",
    col4: "Account Four",
    col5: "00:02:52",
  },
  {
    col1: "origin 5 - Incoming",
    col2: "Gateway 1",
    col3: "Status",
    col4: "Account Five",
    col5: "00:02:45",
  },
  {
    col1: "origin 6 - Incoming",
    col2: "Gateway 1",
    col3: "Status",
    col4: "Account Six",
    col5: "00:04:32",
  },
  {
    col1: "origin 7 - Incoming",
    col2: "Gateway 1",
    col3: "Status",
    col4: "Account Seven",
    col5: "00:04:32",
  },
  {
    col1: "origin 8 - Incoming",
    col2: "Gateway 1",
    col3: "Status",
    col4: "Account Eight",
    col5: "00:04:32",
  },
  {
    col1: "origin 8 - Incoming",
    col2: "Gateway 1",
    col3: "Status",
    col4: "Account Eight",
    col5: "00:04:32",
  },
  {
    col1: "origin 8 - Incoming",
    col2: "Gateway 1",
    col3: "Status",
    col4: "Account Eight",
    col5: "00:04:32",
  },
  {
    col1: "origin 8 - Incoming",
    col2: "Gateway 1",
    col3: "Status",
    col4: "Account Eight",
    col5: "00:04:32",
  },
  {
    col1: "origin 8 - Incoming",
    col2: "Gateway 1",
    col3: "Status",
    col4: "Account Eight",
    col5: "00:04:32",
  },
  {
    col1: "origin 8 - Incoming",
    col2: "Gateway 1",
    col3: "Status",
    col4: "Account Eight",
    col5: "00:04:32",
  },
  {
    col1: "origin 8 - Incoming",
    col2: "Gateway 1",
    col3: "Status",
    col4: "Account Eight",
    col5: "00:04:32",
  },
  {
    col1: "origin 8 - Incoming",
    col2: "Gateway 1",
    col3: "Status",
    col4: "Account Eight",
    col5: "00:04:32",
  },
  {
    col1: "origin 8 - Incoming",
    col2: "Gateway 1",
    col3: "Status",
    col4: "Account Eight",
    col5: "00:04:32",
  },
  {
    col1: "origin 8 - Incoming",
    col2: "Gateway 1",
    col3: "Status",
    col4: "Account Eight",
    col5: "00:04:32",
  },
  {
    col1: "origin 8 - Incoming",
    col2: "Gateway 1",
    col3: "Status",
    col4: "Account Eight",
    col5: "00:04:32",
  },
  {
    col1: "origin 1 - Incoming",
    col2: "Gateway 1",
    col3: "Status",
    col4: "Account One",
    col5: "00:04:32",
  },
  {
    col1: "origin 2 - Incoming",
    col2: "Gateway 1",
    col3: "Status",
    col4: "Account Two",
    col5: "00:03:32",
  },
  {
    col1: "origin 3 - Outgoing",
    col2: "Gateway 2",
    col3: "Status",
    col4: "Account Three",
    col5: "00:03:02",
  },
  {
    col1: "origin 4 - Incoming",
    col2: "Gateway 3",
    col3: "Status",
    col4: "Account Four",
    col5: "00:02:52",
  },
  {
    col1: "origin 5 - Incoming",
    col2: "Gateway 1",
    col3: "Status",
    col4: "Account Five",
    col5: "00:02:45",
  },
  {
    col1: "origin 6 - Incoming",
    col2: "Gateway 1",
    col3: "Status",
    col4: "Account Six",
    col5: "00:04:32",
  },
  {
    col1: "origin 7 - Incoming",
    col2: "Gateway 1",
    col3: "Status",
    col4: "Account Seven",
    col5: "00:04:32",
  },
  {
    col1: "origin 8 - Incoming",
    col2: "Gateway 1",
    col3: "Status",
    col4: "Account Eight",
    col5: "00:04:32",
  },
  {
    col1: "origin 8 - Incoming",
    col2: "Gateway 1",
    col3: "Status",
    col4: "Account Eight",
    col5: "00:04:32",
  },
  {
    col1: "origin 8 - Incoming",
    col2: "Gateway 1",
    col3: "Status",
    col4: "Account Eight",
    col5: "00:04:32",
  },
  {
    col1: "origin 8 - Incoming",
    col2: "Gateway 1",
    col3: "Status",
    col4: "Account Eight",
    col5: "00:04:32",
  },
  {
    col1: "origin 8 - Incoming",
    col2: "Gateway 1",
    col3: "Status",
    col4: "Account Eight",
    col5: "00:04:32",
  },
  {
    col1: "origin 8 - Incoming",
    col2: "Gateway 1",
    col3: "Status",
    col4: "Account Eight",
    col5: "00:04:32",
  },
  {
    col1: "origin 8 - Incoming",
    col2: "Gateway 1",
    col3: "Status",
    col4: "Account Eight",
    col5: "00:04:32",
  },
  {
    col1: "origin 8 - Incoming",
    col2: "Gateway 1",
    col3: "Status",
    col4: "Account Eight",
    col5: "00:04:32",
  },
  {
    col1: "origin 8 - Incoming",
    col2: "Gateway 1",
    col3: "Status",
    col4: "Account Eight",
    col5: "00:04:32",
  },
  {
    col1: "origin 8 - Incoming",
    col2: "Gateway 1",
    col3: "Status",
    col4: "Account Eight",
    col5: "00:04:32",
  },
  {
    col1: "origin 8 - Incoming",
    col2: "Gateway 1",
    col3: "Status",
    col4: "Account Eight",
    col5: "00:04:32",
  },
];
